program         = decl ;

decl            = func_decl ;

func_decl       = "void" ident "(" ")" stmt ;

stmt            =  block | expr ";" ;

block           = "{" { stmt ";" } "}" ;

expr            = funcall | number ;

funcall         = ident "(" expr ")"

number          = ... ;
